### PR TITLE
feat(*): upgrade all 3rd party dependencies and move to modern bundle and tooling

### PR DESCRIPTION
**Pull request by justinrassier**
Modernizing the repo

## Motivation:
The current build creates and es5 build. Modern tooling can't take advantage of tree-shaking and other optimizations. 

Also, it just feels good to be up to date :)

## Overview of changes
* update all dependencies to the latest versions
* Move to eslint instead of TSLint - this came from being unable to resolve TSLint errors after upgrade. 
* Ran eslint --fix on the project to fix auto-fixable issues
* added some eslint-ignore statements for warnings as to not change any source
* Changed the output of the build to es2015
* Added a `tsconfig.es5.json` file for rollup to still create legacy bundles
* Tested agains an Angular 11 project with tests still passing

### CODE REVIEW

**Comment by tylerhubert** [comment]
Hey Justin, it appears that the libs are pulling from IC's Artifactory instead of NPM.  Can you please rectify that?  You can see the build here:  https://travis-ci.org/github/tylerhubert/rsql-criteria-typescript/jobs/749066102

Not sure why the build didn't auto link into here.  It used to do that.

**Comment by justinrassier** [comment]
@tylerhubert ugh, I totally should have thought of that. I will make a note to fix that up. Sorry!

**Comment by justinrassier** [comment]
@tylerhubert all updated and CI passing. Let me know if you need me to do anything else.

**Comment by tylerhubert** [comment]
This all looks good to me.  Support for this repository is supposed to be moved over to the IC repo version of it here: https://github.com/infinitecampus/rsql-criteria-typescript

However, I don't think the automated build/publish out to NPM is setup in the IC version of this yet.  So we can merge this here to create/publish the NPM artifact and then cherry pick the commit over to the IC repo.

**Pull request merged**
